server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Aadhar_User_Registration
    username: root
    password: Password@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true